### ISSUE TITLE
Session URL

### ISSUE THREAD

**Issue by mohsinrizwan** [gierschv/node-ovh-ip#2]
http://www.senchalabs.org/connect/middleware-session.html
unavailable

**Comment by gierschv** [comment]
http://www.senchalabs.org/connect/session.html

**Comment by mohsinrizwan** [comment]
still unable to see how to get randomsrting for session

**Comment by gierschv** [comment]
You just have to generate a random string and put it the config file ("sessSecret: myRandomString").
